# Generated by Django 4.0.1 on 2022-02-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='count',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
